# Generated by Django 2.2 on 2021-04-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0003_posted_comment_posted_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='posted_comment',
            name='posted_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='the_wall_app.Posted_Message'),
        ),
    ]
