# Generated by Django 2.2 on 2021-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0004_posted_comment_posted_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
